### ISSUE TITLE
What about using ResNet Pre-trained weights on IN-1M? 

### ISSUE THREAD

**Issue by Dadatata-JZ** [guybuk/ANCOR#1]
Hi there, 

Thank you so much for sharing this great piece. While I was reading your manuscript and referring to the codes (also MoCo's), a quick question came to me that why the queue and key encoders (resnet) can be not loaded pre-trained weights?

Thank you in advance.

**Comment by guybuk** [comment]
Hello,

Intuitively, a standard pre-trained MoCo model trains on a different objective than the encoder in ANCOR. The MoCo objective pushes features of different images directly away from one-another on the surface of the unit hypersphere, while the ANCOR objective is to push these features away on the orbit relative to a specific coarse class weight (Fig 5. in the paper). As such, the expected result is that a pre-trained MoCo model will have to go through fundamental change to minimize the different training objective in ANCOR.

In practice, we have at one point attempted to use a pre-trained  MoCo model on ImageNet to initialize ANCOR. As expected, the training began with high losses, and while eventually converging to a reasonable model, converged to an inferior model than one started from random.
